name = "GCN_HM_GRN-Integration"
authors = ["Shalin"]

[deps]
BSON = "fbb218c0-5317-5bc6-957e-2ee96dd4b1f0"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia = "1.4.1"
